(type-of-c-reserved-word "double") ;; retorna "Data type"
(type-of-c-reserved-word "if") ;; retorna "Control flow statement"
(type-of-c-reserved-word "interface") ;; retorna "Class or struct keyword"
(type-of-c-reserved-word "// Esto es un comentario") ;; retorna "Comment"
(type-of-c-reserved-word "+") ;; retorna "Operator"
(type-of-c-reserved-word "try") ;; retorna "Exception handling keyword"
(type-of-c-reserved-word "[Obsolete]") ;; retorna "Attribute"
(type-of-c-reserved-word "using") ;; retorna "Miscellaneous keyword"
(type-of-c-reserved-word "foobar") ;; retorna "Not a C# reserved word"
